-- ERP redesign — Phase 7 (make-to-order tail). ADDITIVE ONLY.
-- Adds the three missing downstream entities per §11:
--   • Production + lot traceability: production_orders, production_ops, rm_lots,
--     production_consumption, production_qc (+ scrap/yield feedback edge to costings).
--   • Dispatch / delivery notes: dispatches, dispatch_lines (DN number via the
--     gapless FY-scoped doc_number_series counter; e-way-bill fields).
--   • Invoice / GST: invoices, invoice_lines (CGST/SGST/IGST rate+amount split),
--     credit_notes, payments; gapless FY-scoped invoice number via doc_number_series.
--   • doc_number_series — the per-(seriesKey,fy) gapless counter (lib/series/next-number.ts).
-- Plus additive link columns: sales_orders.negotiation_id (closes the negotiation→SO
-- break), job_cards.{sales_order_item_id,inquiry_item_id,qty_ordered},
-- samples.{inquiry_item_id,item_id}, documents polymorphic FKs
-- (production_order_id/dispatch_id/invoice_id) + template_version.
-- No existing table/column is dropped or renamed. Generated by drizzle-kit and
-- reconciled with meta/0037_snapshot.json (drizzle-kit generate ⇒ No schema changes).
CREATE TYPE "public"."dispatch_status" AS ENUM('draft', 'issued', 'in_transit', 'delivered', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."gst_supply_type" AS ENUM('intra_state', 'inter_state', 'export');--> statement-breakpoint
CREATE TYPE "public"."invoice_status" AS ENUM('draft', 'issued', 'part_paid', 'paid', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."payment_mode" AS ENUM('neft', 'rtgs', 'upi', 'cheque', 'cash', 'card', 'adjustment', 'other');--> statement-breakpoint
CREATE TYPE "public"."production_op_status" AS ENUM('pending', 'in_progress', 'done', 'skipped');--> statement-breakpoint
CREATE TYPE "public"."production_order_status" AS ENUM('planned', 'released', 'in_progress', 'on_hold', 'completed', 'closed', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."production_qc_result" AS ENUM('pending', 'pass', 'fail', 'na');--> statement-breakpoint
CREATE TYPE "public"."rm_lot_status" AS ENUM('available', 'partially_consumed', 'consumed', 'quarantined');--> statement-breakpoint
CREATE SEQUENCE "public"."production_order_no_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 10001 CACHE 1;--> statement-breakpoint
CREATE TABLE "credit_notes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"credit_note_no" text,
	"fy_label" text,
	"invoice_id" uuid,
	"client_id" uuid,
	"credit_note_date" timestamp with time zone,
	"reason" text,
	"supply_type" "gst_supply_type",
	"sub_total" numeric,
	"cgst_total" numeric,
	"sgst_total" numeric,
	"igst_total" numeric,
	"tax_total" numeric,
	"grand_total" numeric,
	"notes" text,
	"issued_at" timestamp with time zone,
	"created_by_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "credit_notes_credit_note_no_unique" UNIQUE("credit_note_no")
);
--> statement-breakpoint
CREATE TABLE "dispatch_lines" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"dispatch_id" uuid NOT NULL,
	"sales_order_item_id" uuid,
	"item_id" uuid,
	"production_order_id" uuid,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"qty_dispatched" numeric NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dispatches" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"dn_no" text,
	"fy_label" text,
	"dispatch_date" timestamp with time zone,
	"client_id" uuid,
	"sales_order_id" uuid,
	"status" "dispatch_status" DEFAULT 'draft' NOT NULL,
	"vehicle_no" text,
	"transporter_name" text,
	"lr_no" text,
	"eway_bill_no" text,
	"eway_bill_date" timestamp with time zone,
	"ship_to_address" text,
	"notes" text,
	"issued_at" timestamp with time zone,
	"issued_by_id" uuid,
	"created_by_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "dispatches_dn_no_unique" UNIQUE("dn_no")
);
--> statement-breakpoint
CREATE TABLE "doc_number_series" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"series_key" text NOT NULL,
	"fy_label" text NOT NULL,
	"prefix" text DEFAULT '' NOT NULL,
	"pad_to" integer DEFAULT 4 NOT NULL,
	"last_value" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "invoice_lines" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"invoice_id" uuid NOT NULL,
	"item_id" uuid,
	"sales_order_item_id" uuid,
	"dispatch_line_id" uuid,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"description" text,
	"hsn_code" text,
	"uom" text DEFAULT 'Nos',
	"qty" numeric NOT NULL,
	"unit_price" numeric NOT NULL,
	"discount" numeric DEFAULT '0' NOT NULL,
	"taxable_value" numeric NOT NULL,
	"tax_rate" numeric DEFAULT '0' NOT NULL,
	"cgst_rate" numeric DEFAULT '0' NOT NULL,
	"cgst_amount" numeric DEFAULT '0' NOT NULL,
	"sgst_rate" numeric DEFAULT '0' NOT NULL,
	"sgst_amount" numeric DEFAULT '0' NOT NULL,
	"igst_rate" numeric DEFAULT '0' NOT NULL,
	"igst_amount" numeric DEFAULT '0' NOT NULL,
	"line_total" numeric NOT NULL,
	"spec_snapshot" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "invoices" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"invoice_no" text,
	"fy_label" text,
	"invoice_date" timestamp with time zone,
	"client_id" uuid,
	"sales_order_id" uuid,
	"dispatch_id" uuid,
	"status" "invoice_status" DEFAULT 'draft' NOT NULL,
	"place_of_supply" text,
	"seller_state" text,
	"supply_type" "gst_supply_type",
	"is_inter_state" boolean,
	"seller_gstin" text,
	"buyer_gstin" text,
	"sub_total" numeric,
	"cgst_total" numeric,
	"sgst_total" numeric,
	"igst_total" numeric,
	"tax_total" numeric,
	"grand_total" numeric,
	"round_off" numeric,
	"amount_paid" numeric DEFAULT '0' NOT NULL,
	"irn" text,
	"irn_ack_no" text,
	"irn_ack_date" timestamp with time zone,
	"template_version" text,
	"notes" text,
	"issued_at" timestamp with time zone,
	"issued_by_id" uuid,
	"created_by_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "invoices_invoice_no_unique" UNIQUE("invoice_no")
);
--> statement-breakpoint
CREATE TABLE "payments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"invoice_id" uuid,
	"client_id" uuid,
	"amount" numeric NOT NULL,
	"mode" "payment_mode" DEFAULT 'neft' NOT NULL,
	"reference" text,
	"paid_at" timestamp with time zone DEFAULT now() NOT NULL,
	"notes" text,
	"created_by_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production_consumption" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"production_order_id" uuid NOT NULL,
	"production_op_id" uuid,
	"rm_lot_id" uuid NOT NULL,
	"qty_consumed_kg" numeric NOT NULL,
	"consumed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"notes" text,
	"created_by_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production_ops" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"production_order_id" uuid NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"op_name" text NOT NULL,
	"work_center" text,
	"status" "production_op_status" DEFAULT 'pending' NOT NULL,
	"planned_mins" numeric,
	"actual_mins" numeric,
	"operator_id" uuid,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "production_orders" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"po_no" text DEFAULT 'PO-' || nextval('production_order_no_seq') NOT NULL,
	"sales_order_id" uuid,
	"sales_order_item_id" uuid,
	"job_card_id" uuid,
	"item_id" uuid NOT NULL,
	"status" "production_order_status" DEFAULT 'planned' NOT NULL,
	"qty_planned" numeric,
	"qty_produced" numeric,
	"scrap_qty" numeric,
	"yield_pct" numeric,
	"actual_rm_kg" numeric,
	"costing_id" uuid,
	"cost_feedback_notes" text,
	"planned_start_date" timestamp with time zone,
	"planned_end_date" timestamp with time zone,
	"actual_start_date" timestamp with time zone,
	"actual_end_date" timestamp with time zone,
	"notes" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_by_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "production_orders_po_no_unique" UNIQUE("po_no")
);
--> statement-breakpoint
CREATE TABLE "production_qc" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"production_order_id" uuid NOT NULL,
	"rm_lot_id" uuid,
	"check_name" text NOT NULL,
	"result" "production_qc_result" DEFAULT 'pending' NOT NULL,
	"measured_value" text,
	"spec" text,
	"checked_by_id" uuid,
	"checked_at" timestamp with time zone,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rm_lots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"lot_no" text NOT NULL,
	"heat_no" text,
	"grade" text,
	"internal_grade_id" uuid,
	"supplier_name" text,
	"qty_received_kg" numeric,
	"qty_remaining_kg" numeric,
	"unit_cost_per_kg" numeric,
	"received_date" timestamp with time zone,
	"status" "rm_lot_status" DEFAULT 'available' NOT NULL,
	"notes" text,
	"created_by_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "production_order_id" uuid;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "dispatch_id" uuid;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "invoice_id" uuid;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "template_version" text;--> statement-breakpoint
ALTER TABLE "job_cards" ADD COLUMN "sales_order_item_id" uuid;--> statement-breakpoint
ALTER TABLE "job_cards" ADD COLUMN "inquiry_item_id" uuid;--> statement-breakpoint
ALTER TABLE "job_cards" ADD COLUMN "qty_ordered" numeric;--> statement-breakpoint
ALTER TABLE "sales_orders" ADD COLUMN "negotiation_id" uuid;--> statement-breakpoint
ALTER TABLE "samples" ADD COLUMN "inquiry_item_id" uuid;--> statement-breakpoint
ALTER TABLE "samples" ADD COLUMN "item_id" uuid;--> statement-breakpoint
ALTER TABLE "credit_notes" ADD CONSTRAINT "credit_notes_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "credit_notes" ADD CONSTRAINT "credit_notes_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "credit_notes" ADD CONSTRAINT "credit_notes_created_by_id_employees_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."employees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dispatch_lines" ADD CONSTRAINT "dispatch_lines_dispatch_id_dispatches_id_fk" FOREIGN KEY ("dispatch_id") REFERENCES "public"."dispatches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dispatch_lines" ADD CONSTRAINT "dispatch_lines_sales_order_item_id_sales_order_items_id_fk" FOREIGN KEY ("sales_order_item_id") REFERENCES "public"."sales_order_items"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dispatch_lines" ADD CONSTRAINT "dispatch_lines_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dispatch_lines" ADD CONSTRAINT "dispatch_lines_production_order_id_production_orders_id_fk" FOREIGN KEY ("production_order_id") REFERENCES "public"."production_orders"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dispatches" ADD CONSTRAINT "dispatches_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dispatches" ADD CONSTRAINT "dispatches_sales_order_id_sales_orders_id_fk" FOREIGN KEY ("sales_order_id") REFERENCES "public"."sales_orders"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dispatches" ADD CONSTRAINT "dispatches_issued_by_id_employees_id_fk" FOREIGN KEY ("issued_by_id") REFERENCES "public"."employees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dispatches" ADD CONSTRAINT "dispatches_created_by_id_employees_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."employees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoice_lines" ADD CONSTRAINT "invoice_lines_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoice_lines" ADD CONSTRAINT "invoice_lines_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoice_lines" ADD CONSTRAINT "invoice_lines_sales_order_item_id_sales_order_items_id_fk" FOREIGN KEY ("sales_order_item_id") REFERENCES "public"."sales_order_items"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoice_lines" ADD CONSTRAINT "invoice_lines_dispatch_line_id_dispatch_lines_id_fk" FOREIGN KEY ("dispatch_line_id") REFERENCES "public"."dispatch_lines"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_sales_order_id_sales_orders_id_fk" FOREIGN KEY ("sales_order_id") REFERENCES "public"."sales_orders"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_dispatch_id_dispatches_id_fk" FOREIGN KEY ("dispatch_id") REFERENCES "public"."dispatches"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_issued_by_id_employees_id_fk" FOREIGN KEY ("issued_by_id") REFERENCES "public"."employees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_created_by_id_employees_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."employees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_created_by_id_employees_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."employees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_consumption" ADD CONSTRAINT "production_consumption_production_order_id_production_orders_id_fk" FOREIGN KEY ("production_order_id") REFERENCES "public"."production_orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_consumption" ADD CONSTRAINT "production_consumption_production_op_id_production_ops_id_fk" FOREIGN KEY ("production_op_id") REFERENCES "public"."production_ops"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_consumption" ADD CONSTRAINT "production_consumption_rm_lot_id_rm_lots_id_fk" FOREIGN KEY ("rm_lot_id") REFERENCES "public"."rm_lots"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_consumption" ADD CONSTRAINT "production_consumption_created_by_id_employees_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."employees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_ops" ADD CONSTRAINT "production_ops_production_order_id_production_orders_id_fk" FOREIGN KEY ("production_order_id") REFERENCES "public"."production_orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_ops" ADD CONSTRAINT "production_ops_operator_id_employees_id_fk" FOREIGN KEY ("operator_id") REFERENCES "public"."employees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_orders" ADD CONSTRAINT "production_orders_sales_order_id_sales_orders_id_fk" FOREIGN KEY ("sales_order_id") REFERENCES "public"."sales_orders"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_orders" ADD CONSTRAINT "production_orders_sales_order_item_id_sales_order_items_id_fk" FOREIGN KEY ("sales_order_item_id") REFERENCES "public"."sales_order_items"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_orders" ADD CONSTRAINT "production_orders_job_card_id_job_cards_id_fk" FOREIGN KEY ("job_card_id") REFERENCES "public"."job_cards"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_orders" ADD CONSTRAINT "production_orders_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_orders" ADD CONSTRAINT "production_orders_costing_id_costings_id_fk" FOREIGN KEY ("costing_id") REFERENCES "public"."costings"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_orders" ADD CONSTRAINT "production_orders_created_by_id_employees_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."employees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_qc" ADD CONSTRAINT "production_qc_production_order_id_production_orders_id_fk" FOREIGN KEY ("production_order_id") REFERENCES "public"."production_orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_qc" ADD CONSTRAINT "production_qc_rm_lot_id_rm_lots_id_fk" FOREIGN KEY ("rm_lot_id") REFERENCES "public"."rm_lots"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_qc" ADD CONSTRAINT "production_qc_checked_by_id_employees_id_fk" FOREIGN KEY ("checked_by_id") REFERENCES "public"."employees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rm_lots" ADD CONSTRAINT "rm_lots_internal_grade_id_master_options_id_fk" FOREIGN KEY ("internal_grade_id") REFERENCES "public"."master_options"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rm_lots" ADD CONSTRAINT "rm_lots_created_by_id_employees_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."employees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "credit_notes_invoice_idx" ON "credit_notes" USING btree ("invoice_id");--> statement-breakpoint
CREATE INDEX "credit_notes_client_idx" ON "credit_notes" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "credit_notes_fy_idx" ON "credit_notes" USING btree ("fy_label");--> statement-breakpoint
CREATE INDEX "dispatch_lines_dispatch_idx" ON "dispatch_lines" USING btree ("dispatch_id","sort_order");--> statement-breakpoint
CREATE INDEX "dispatch_lines_item_idx" ON "dispatch_lines" USING btree ("item_id");--> statement-breakpoint
CREATE INDEX "dispatch_lines_so_item_idx" ON "dispatch_lines" USING btree ("sales_order_item_id");--> statement-breakpoint
CREATE INDEX "dispatches_client_idx" ON "dispatches" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "dispatches_so_idx" ON "dispatches" USING btree ("sales_order_id");--> statement-breakpoint
CREATE INDEX "dispatches_status_idx" ON "dispatches" USING btree ("status");--> statement-breakpoint
CREATE INDEX "dispatches_fy_idx" ON "dispatches" USING btree ("fy_label");--> statement-breakpoint
CREATE UNIQUE INDEX "doc_number_series_key_fy_uidx" ON "doc_number_series" USING btree ("series_key","fy_label");--> statement-breakpoint
CREATE INDEX "invoice_lines_invoice_idx" ON "invoice_lines" USING btree ("invoice_id","sort_order");--> statement-breakpoint
CREATE INDEX "invoice_lines_item_idx" ON "invoice_lines" USING btree ("item_id");--> statement-breakpoint
CREATE INDEX "invoices_client_idx" ON "invoices" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "invoices_so_idx" ON "invoices" USING btree ("sales_order_id");--> statement-breakpoint
CREATE INDEX "invoices_status_idx" ON "invoices" USING btree ("status");--> statement-breakpoint
CREATE INDEX "invoices_fy_idx" ON "invoices" USING btree ("fy_label");--> statement-breakpoint
CREATE INDEX "payments_invoice_idx" ON "payments" USING btree ("invoice_id");--> statement-breakpoint
CREATE INDEX "payments_client_idx" ON "payments" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "production_consumption_order_idx" ON "production_consumption" USING btree ("production_order_id");--> statement-breakpoint
CREATE INDEX "production_consumption_lot_idx" ON "production_consumption" USING btree ("rm_lot_id");--> statement-breakpoint
CREATE INDEX "production_ops_order_idx" ON "production_ops" USING btree ("production_order_id","sort_order");--> statement-breakpoint
CREATE INDEX "production_orders_item_idx" ON "production_orders" USING btree ("item_id");--> statement-breakpoint
CREATE INDEX "production_orders_so_idx" ON "production_orders" USING btree ("sales_order_id");--> statement-breakpoint
CREATE INDEX "production_orders_so_item_idx" ON "production_orders" USING btree ("sales_order_item_id");--> statement-breakpoint
CREATE INDEX "production_orders_job_card_idx" ON "production_orders" USING btree ("job_card_id");--> statement-breakpoint
CREATE INDEX "production_orders_status_idx" ON "production_orders" USING btree ("status");--> statement-breakpoint
CREATE INDEX "production_orders_costing_idx" ON "production_orders" USING btree ("costing_id");--> statement-breakpoint
CREATE INDEX "production_qc_order_idx" ON "production_qc" USING btree ("production_order_id");--> statement-breakpoint
CREATE INDEX "production_qc_lot_idx" ON "production_qc" USING btree ("rm_lot_id");--> statement-breakpoint
CREATE UNIQUE INDEX "rm_lots_lot_no_uidx" ON "rm_lots" USING btree (lower("lot_no"));--> statement-breakpoint
CREATE INDEX "rm_lots_grade_idx" ON "rm_lots" USING btree ("internal_grade_id");--> statement-breakpoint
CREATE INDEX "rm_lots_status_idx" ON "rm_lots" USING btree ("status");--> statement-breakpoint
ALTER TABLE "documents" ADD CONSTRAINT "documents_production_order_id_production_orders_id_fk" FOREIGN KEY ("production_order_id") REFERENCES "public"."production_orders"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "documents" ADD CONSTRAINT "documents_dispatch_id_dispatches_id_fk" FOREIGN KEY ("dispatch_id") REFERENCES "public"."dispatches"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "documents" ADD CONSTRAINT "documents_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "job_cards" ADD CONSTRAINT "job_cards_sales_order_item_id_sales_order_items_id_fk" FOREIGN KEY ("sales_order_item_id") REFERENCES "public"."sales_order_items"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "job_cards" ADD CONSTRAINT "job_cards_inquiry_item_id_inquiry_items_id_fk" FOREIGN KEY ("inquiry_item_id") REFERENCES "public"."inquiry_items"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales_orders" ADD CONSTRAINT "sales_orders_negotiation_id_negotiations_id_fk" FOREIGN KEY ("negotiation_id") REFERENCES "public"."negotiations"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samples" ADD CONSTRAINT "samples_inquiry_item_id_inquiry_items_id_fk" FOREIGN KEY ("inquiry_item_id") REFERENCES "public"."inquiry_items"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "samples" ADD CONSTRAINT "samples_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "documents_production_order_idx" ON "documents" USING btree ("production_order_id");--> statement-breakpoint
CREATE INDEX "documents_dispatch_idx" ON "documents" USING btree ("dispatch_id");--> statement-breakpoint
CREATE INDEX "documents_invoice_idx" ON "documents" USING btree ("invoice_id");--> statement-breakpoint
CREATE INDEX "job_cards_so_item_idx" ON "job_cards" USING btree ("sales_order_item_id");--> statement-breakpoint
CREATE INDEX "job_cards_inquiry_item_idx" ON "job_cards" USING btree ("inquiry_item_id");--> statement-breakpoint
CREATE INDEX "sales_orders_negotiation_idx" ON "sales_orders" USING btree ("negotiation_id");--> statement-breakpoint
CREATE INDEX "samples_item_idx" ON "samples" USING btree ("item_id");--> statement-breakpoint
CREATE INDEX "samples_inquiry_item_idx" ON "samples" USING btree ("inquiry_item_id");