import { VendorForm } from "@/components/vendors/vendor-form";
import { requireAdmin } from "@/lib/auth/current";
import { listMasterOptions } from "@/lib/queries/masters";
import { EnquiryModuleShell } from "@/components/enquiries/enquiry-module-shell";
import { UserMenuServer } from "@/components/header/user-menu-server";

export const dynamic = "force-dynamic";

/**
 * New Vendor (Forms module) — admin-only create form. The human vendorCode
 * (VN-####) is auto-generated by the DB on insert. Saves via VendorForm with
 * basePath="/vendors" so it returns to the Forms-module vendor record. Payment
 * Terms are picked from the admin-managed master ("already set" options).
 */
export default async function NewVendorPage() {
  await requireAdmin();
  const paymentTerms = await listMasterOptions("payment_term");
  const paymentTermsOptions = paymentTerms.map((o) => ({
    value: o.name,
    label: o.name,
  }));

  return (
    <EnquiryModuleShell title="Vendors" userMenu={<UserMenuServer />}>
      <div className="mx-auto w-full max-w-[900px]">
        <header className="mb-5">
          <h1 className="text-[26px] font-black leading-none tracking-tight text-[#3f3f94]">
            New Vendor
          </h1>
        </header>

        <VendorForm basePath="/vendors" paymentTermsOptions={paymentTermsOptions} />
      </div>
    </EnquiryModuleShell>
  );
}
