import Link from "next/link";
import type { Route } from "next";
import { ArrowLeft } from "lucide-react";
import { VendorForm } from "@/components/vendors/vendor-form";
import { requireAdmin } from "@/lib/auth/current";
import { EnquiryModuleShell } from "@/components/enquiries/enquiry-module-shell";
import { UserMenuServer } from "@/components/header/user-menu-server";

export const dynamic = "force-dynamic";

/**
 * New Vendor (Forms module) — admin-only create form. The human vendorCode
 * (VN-####) is auto-generated by the DB on insert. Saves via VendorForm with
 * basePath="/vendors" so it returns to the Forms-module vendor record.
 */
export default async function NewVendorPage() {
  await requireAdmin();

  return (
    <EnquiryModuleShell title="Vendors" userMenu={<UserMenuServer />}>
      <div className="mx-auto w-full max-w-[900px]">
        <header className="mb-5">
          <Link
            href={"/vendors" as Route}
            className="inline-flex items-center gap-1.5 text-[13px] font-semibold text-[#6b7280] transition-colors hover:text-[#3f3f94]"
          >
            <ArrowLeft size={15} strokeWidth={2.4} />
            Vendors
          </Link>
          <h1 className="mt-2 text-[26px] font-black leading-none tracking-tight text-[#3f3f94]">
            New Vendor
          </h1>
        </header>

        <VendorForm basePath="/vendors" />
      </div>
    </EnquiryModuleShell>
  );
}
